name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u harshita61 --password-stdin

      - name: Build Image
        run: docker build -t harshita61/exp6-app:latest .

      - name: Push Image
        run: docker push harshita61/exp6-app:latest